### ISSUE TITLE
Incompatibility with FastCraft+

### ISSUE THREAD

**Issue by nshtg** [ericpauley/MagicChest#4]
I saw you updated it to work with the newest version of FastCraft+, but it still moves items around as soon as you open it:

![2016-05-28_18 55 35](https://cloud.githubusercontent.com/assets/5219415/15628624/de90f60a-2505-11e6-8a9e-19d8b5a3f356.png)

Disabling MagicChest fixes the problems.

**Comment by uvbeenzaned** [comment]
I am going to revisit this issue. Seems as though I have not implemented the API properly since @BenWoodworth has moved to FastCraftPlus.

**Comment by BenWoodworth** [comment]
Hi. You will have to use the FastCraft+ API for compatibility.

https://github.com/BenWoodworth/FastCraftPlus/blob/master/src/main/java/co/kepler/fastcraftplus/api/FastCraftAPI.java#L18

You can use this method to see if an inventory is a FastCraft+ GUI, and if it is, you can leave it alone.

**Comment by uvbeenzaned** [comment]
@BenWoodworth excuse me for wasting your time! I just found where I had updated everything but your plugin name string in the place where I pull your instance of FastCraftPlus from the bukkit API. @nshtg I will try to have a fix out tonight for you, sorry for the inconvenience. I will send you the build directly so that you can test and report back to me. I have no time or the setup to test at the hotel I'm staying at.

**Comment by BenWoodworth** [comment]
No worries, I'm not too busy. Let me know if you need any help using the API.

**Comment by uvbeenzaned** [comment]
@BenWoodworth Thanks for your quick response!

**Comment by uvbeenzaned** [comment]
@nshtg Please try this build out and report back to me on compat! Thanks!

http://dw.networkery.co/bukkitdev/MagicChest/MagicChest.jar

**Comment by nshtg** [comment]
@uvbeenzaned 
It's fixed with that version. Thank you!

**Comment by uvbeenzaned** [comment]
@nshtg You are welcome! I will be releasing this version on BukkitDev along with updated MetricsLite and an incremented build number.

**Comment by BenWoodworth** [comment]
It looks like there are still some FastCraft+ compatibility issues. I recently changed the name of the main class from FastCraft to FastCraftPlus. This is causing some issues when your plugin starts up. I think to fix this, you just need to change the name of the class you reference in your compatibility code.

https://github.com/BenWoodworth/FastCraftPlus/issues/80#issuecomment-232122171

**Comment by uvbeenzaned** [comment]
I will look at it as soon as possible. I hope we can finally put this one to bed.

**Comment by BenWoodworth** [comment]
Here's a checklist to get everything working :
- [ ] Change FastCraft to FastCraftPlus: https://github.com/ericpauley/MagicChest/blob/master/src/org/zonedabone/magicchest/PluginCompatibility.java#L46-L53
- [ ] Change isFastCraftGUI to isGUI: https://github.com/ericpauley/MagicChest/blob/master/src/org/zonedabone/magicchest/PluginCompatibility.java#L112
- [ ] Run Magic Chest and FastCraft+ on a test server to test compatibilty.

**Comment by uvbeenzaned** [comment]
Working on this right now... At this very moment finally...

**Comment by uvbeenzaned** [comment]
This line is not actually the problem. - https://github.com/ericpauley/MagicChest/blob/master/src/org/zonedabone/magicchest/PluginCompatibility.java#L46

However, this line is the one that needed changes - https://github.com/ericpauley/MagicChest/commit/96725c771ea775a29a4a6d4e93f84f1f074c83dd#diff-2da534dcd4eeeb0b97d0c7b94f73bcdcR90

Your main class in your plugin does not seem to be named FastCraftPlus but as I have it in the plugin already. Like I said though the API line was wrong I have fixed it as requested in the above commit line reference.

**Comment by BenWoodworth** [comment]
In a recent release the main class was renamed to FastCraftPlus. Make sure
you're using v0.24, the most recent release.

**Comment by uvbeenzaned** [comment]
Not to seem stupid or anything but I just checked your last commit and compared it with your last jar on BukkitDev and the code doesn't match. I decompiled the last jar file from BukkitDev to check this. It seems you may have not compiled with the latest code maybe?

Decompiled class list with mismatched name - http://prntscr.com/bu6afp

Version proof - http://prntscr.com/bu6aop

My IDE claims that with your current version 0.24.3, that "FastCraft" is a valid reference, however "FastCraftPlus" is invalid and won't compile. I assure you that I have updated your JAR file and I have made sure that I am pointing to the latest.

**Comment by BenWoodworth** [comment]
I figured out what's happening. In the midst recent release it's still
FastCraft. It's been a month since I pushed a release, so I thought it was
FastCraftPlus in the releases. You can probably remove the instanceof
check, since you're not using it for anything other than verifying the
plugin.

**Comment by uvbeenzaned** [comment]
OK I see. One question though, for this release though wouldn't my check still technically be valid since that is what you release to the public? I mean it seems like everything checks out on my end. Were you planning on changing it later?

If you were planning on changing it soon, you can notify me ahead of time and give me the JAR before release and you and I can release at the same time to make the transition go smoother.

I can remove that check but it lets the user be sure that my plugin really picked yours up and it also is a safety net so that my plugin won't try to use your API in any way if your plugin is not loaded.

Your call though!

Thanks!

**Comment by BenWoodworth** [comment]
I can let you know before I release the next version. I'll send you the jar
beforehand.

**Comment by uvbeenzaned** [comment]
Ok so I what I will do is release under my most current commit with the "FastCraft" reference for now and we'll call it a wrap.

**Comment by BenWoodworth** [comment]
Sounds good. I'll upload the release to this issue when it's ready.

**Comment by uvbeenzaned** [comment]
Also, please read the bottom of my comment above, need suggestions.

**Comment by BenWoodworth** [comment]
Try putting this in your permissions.yml file:
```
server.basics:
       description: Basic permissions for My Cool Server.
       default: true
       children:
          fastcraft.use
          fastcraft.command.*
```

**Comment by uvbeenzaned** [comment]
Ok I'll do that.

**Comment by BenWoodworth** [comment]
Just another idea I had. Instead of using instanceof to verify it's the correct plugin, you can use Main from the plugin.yml:

```
...
Main: co.kepler.fastcraftplus.FastCraftPlus
...
```

You can check if the string starts with "co.kepler.fastcraftplus". You won't have to worry about me changing the main class name, and this code will be compatible with any version of FastCraft+.

**Comment by uvbeenzaned** [comment]
That's not a bad idea. I have not release the plugin as of yet so I will see if I can implement that. It will be a less solid way but it will still ensure that some part of your plugin is loaded.

**Comment by BenWoodworth** [comment]
Alright. Let me know what you decide on. I'll send you the jar early if you decide to use instanceof.

**Comment by BenWoodworth** [comment]
I just released FastCraft+ v0.25
https://github.com/BenWoodworth/FastCraftPlus/releases/download/v0.25/FastCraftPlus.jar

**Comment by uvbeenzaned** [comment]
I will see if I can get a release out for this later today.

**Comment by uvbeenzaned** [comment]
I have to implement a whole new PluginCompat class to be able to do things like we talked about above so for now I have committed and released an update to get people by. I will have to make time to rewrite that class in the near future.
